// <auto-generated />
using DAB_Assignment_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAB_Assignment_2.Migrations
{
    [DbContext(typeof(myDbContext))]
    [Migration("20200331124144_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAB_Assignment_2.Models.Assignment", b =>
                {
                    b.Property<string>("lecture")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.Property<string>("helpwhere")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lecture", "number");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("DAB_Assignment_2.Models.Attends", b =>
                {
                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Semester");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attends");
                });

            modelBuilder.Entity("DAB_Assignment_2.Models.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("courseId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("DAB_Assignment_2.Models.Exercise", b =>
                {
                    b.Property<string>("lecture")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.Property<string>("StudentAUid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("helpwhere")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lecture", "number");

                    b.HasIndex("StudentAUid");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("DAB_Assignment_2.Models.RequestHelpAssignments", b =>
                {
                    b.Property<int>("RequestHelpAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssignmentHelpWhere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignmentLecture")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssignmentNumber")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestHelpAssignmentID");

                    b.HasIndex("StudentId");

                    b.HasIndex("AssignmentLecture", "AssignmentNumber");

                    b.ToTable("RequestHelpAssignments");
                });

            modelBuilder.Entity("DAB_Assignment_2.Models.Student", b =>
                {
                    b.Property<string>("StudentAUid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentAUid");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("DAB_Assignment_2.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherAUid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherAUid");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("DAB_Assignment_2.Models.Attends", b =>
                {
                    b.HasOne("DAB_Assignment_2.Models.Course", "Course")
                        .WithMany("Attends")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAB_Assignment_2.Models.Student", "Student")
                        .WithMany("Attends")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("DAB_Assignment_2.Models.Exercise", b =>
                {
                    b.HasOne("DAB_Assignment_2.Models.Student", "student")
                        .WithMany("Exercises")
                        .HasForeignKey("StudentAUid");
                });

            modelBuilder.Entity("DAB_Assignment_2.Models.RequestHelpAssignments", b =>
                {
                    b.HasOne("DAB_Assignment_2.Models.Student", "Student")
                        .WithMany("RequestHelpAssignments")
                        .HasForeignKey("StudentId");

                    b.HasOne("DAB_Assignment_2.Models.Assignment", "Assignment")
                        .WithMany("RequestHelpAssignmentses")
                        .HasForeignKey("AssignmentLecture", "AssignmentNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
